name:                haskell-crawler
version:             0.1.0.0
github:              "githubuser/haskell-crawler"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-crawler#readme>

dependencies:
- base == 4.12.0.0 # standard library
- either >= 5.0.1.1 # Data.Either utils
- wai == 3.2.2.1 # http server
- warp == 3.2.28 # http server
- http-types == 0.12.3 # http server
- bytestring == 0.10.8.2
- lens == 4.17.1 # api for http client
- wreq == 0.5.3.2 # http client
- parsec >= 3.1.13.0 # parsing
- aeson >= 1.4.5.0

library:
  source-dirs: src

executables:
  haskell-crawler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-crawler

tests:
  haskell-crawler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-crawler
